--liquibase formatted sql
--changeset alex:2
DROP TABLE IF EXISTS public.characteristics;
CREATE TABLE IF NOT EXISTS public.characteristics
(
    code character varying(5) COLLATE pg_catalog."default" NOT NULL,
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    characteristic_type character varying(255) COLLATE pg_catalog."default",
    characteristic_value character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT characteristics_pkey PRIMARY KEY (id),
    CONSTRAINT characteristics_characteristic_type_check CHECK (characteristic_type::text = ANY (ARRAY['CONSUMPTION_TYPE'::character varying, 'CHARGING_POINT'::character varying, 'CONNECTION_POINT_STATUS'::character varying]::text[]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.characteristics
    OWNER to sa;
