--liquibase formatted sql
--changeset alex:3
DROP TABLE IF EXISTS public.resources;
CREATE TABLE IF NOT EXISTS public.resources
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    location_id bigint,
    country_code character varying(255) COLLATE pg_catalog."default",
    resource_type character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT resources_pkey PRIMARY KEY (id),
    CONSTRAINT fk9mh1p47vsfjrfqpidv50acqg0 FOREIGN KEY (location_id)
        REFERENCES public.locations (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT resources_resource_type_check CHECK (resource_type::text = ANY (ARRAY['METERING_POINT'::character varying, 'CONNECTION_POINT'::character varying]::text[]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.resources
    OWNER to sa;
